### ISSUE TITLE
dependency on your assertion module

### ISSUE THREAD

**Issue by schollii** [Invicton-Labs/terraform-null-deepmerge#1]
Hi this is so far a great module, did the job and seems like a robust strategy for nested maps (I did not check how it will handle lists). Thanks for sharing this. One issue: 

There is a dependency on your `assertion` module which prevents use of your `deepmerge` module *from the terraform registry* because it has a hardcoded source path of "../assert" to assert the merge worked. The assertion is a good thing in itself, but you need to fix this. There are a few of ways I can think of, don't know which one you would prefer so I can't submit a PR:
 
- use the very popular "assert" module that is available in the terraform registry: https://registry.terraform.io/modules/kchugalinskiy/assert/null/latest
- publish your `assertion` module and reference it via registry instead of relative local path
- include your assertion module as a submodule, and change `../assert` to `./assert`

Meanwhile, my workaround was that I downloaded a gzip of your two modules (deepmerge and assertion), unzipped them in a subfolder of my own module, and renamed the assertion folder to "assert". My code looks like this: 
```
my-tf-module
  inviction-lab
     assert
     deepmerge
     README.md // I point to your github
  main.tf
  ...
```

**Comment by KyleKotowick** [comment]
Ah, sorry about that! The assertion module was already published in the registry, but I hadn't updated this code yet. The new release (v0.1.1) should be good.
